version: '3.2'
services:
  relay:
    build: . 
    image: eftechcombr/postfix:latest
    restart: unless-stopped
    volumes:
      - postfix-volume:/var/spool/postfix
    ports:
      - "30025:25"
    env_file: ./.env
volumes:
  postfix-volume:
