---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postfix
  name: postfix
spec:
  ports:
  - name: postfix
    port: 25
    protocol: TCP
    targetPort: 25
  selector:
    app: postfix
  type: ClusterIP
status:
  loadBalancer: {}
