apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# nameSuffix: -sandbox
# namespace: sandbox

resources:
- deployment.yaml
- service.yaml


images:
- name: eftechcombr/postfix
  newName: eftechcombr/postfix
  newTag: dev