apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postfix
  name: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postfix
    spec:
      containers:
      - image: eftechcombr/postfix:latest
        name: postfix
        ports:
        - containerPort: 25
        resources: {}
status: {}