name: Dispatch to IaC

on:
  workflow_run:
    workflows: ["Build and Publish"]
    types:
      - completed
    branches: 
      - latest

env: 
  REPO_DESTINATION: "eftechcombr/iac"
  PATH_DESTINATION: "files/kubernetes/prod/postfix"

jobs:

  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: create a repository_dispatch event
        run: |
          TOKEN=${{ secrets.PAT_TOKEN }}
          curl -X POST \
          -H "Authorization: token $TOKEN" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -d '{ "event_type": "update-repo", "client_payload": { "sha": "${{ github.sha }}", "from": "${{ github.repository}}", "branch": "${{ github.ref_name}}", "destination": "${{ env.PATH_DESTINATION }}" } }' \
          https://api.github.com/repos/${{ env.REPO_DESTINATION }}/dispatches


          