name: Dispatch to IaC

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Publish"]
    types:
      - completed
    branches: 
      - latest

env: 
  DESTINATION_OWNER: "eftechcombr"
  DESTINATION_REPO: "iac"
  DESTINATION_PATH: "files/kubernetes/prod/postfix"

jobs:

  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Use the token
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api octocat

      - name: create a repository_dispatch event
        id: post_dispatches
        uses: octokit/request-action@v2.x
        if: ${{ github.ref_name }} == 'dev' 
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}    

        with:
          route: POST /repos/${{ env.DESTINATION_OWNER }}/${{ env.DESTINATION_REPO }}/dispatches
          data: '{
            event_type: "update-repo", 
            client_payload: {
              sha: "${{ github.sha }}", 
              from: "${{ github.repository}}", 
              branch: "${{ github.ref_name}}", 
              destination: "${{ env.DESTINATION_PATH }}"
            }
          }'
            
  
