name: Dispatch to IaC

on:
  workflow_run:
    workflows: ["Build and Publish"]
    types:
      - completed
    branches: 
      - latest

jobs:

  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: create a repository_dispatch event
        run: |
          TOKEN=${{ secrets.PAT_TOKEN }}
          curl -X POST \
          -H "Authorization: token $TOKEN" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -d '{"event_type": "update-repo"}' \
          https://api.github.com/repos/eftechcombr/postfix-configuration/dispatches


          