name: Create Pull Request to latest

on:
  workflow_run:
    workflows: ["Build and Publish"]
    types:
      - completed
    branches: 
      - dev

jobs:

  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: latest

      - name: Reset dev branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev
       
      - name: Replace image Tag 
        run: |
          sed -i "s/newTag: latest/newTag: ${{ github.sha }}/" infra/kubernetes/kustomization.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: dev

